### PR TITLE
Delete JSON.sh and use JQ

### PR DESCRIPTION
**Pull request by otgo**
That's best, ¿Why not using JQ ?

Features:

- UTF-8 full
- All emojis compatibles
- More speed

### CODE REVIEW

**Comment by topkecleon** [comment]
Another binary dependency?

**Comment by JuanPotato** [comment]
oh boy

**Comment by jarriztg** [comment]
Just JQ, don't worry

**Comment by topkecleon** [comment]
I'll let @danog decide whether or not the performance boost outweighs the portability hit.

**Comment by danog** [comment]
the process_client function is faster by a mere tenth of a second, and processing of multiple updates simultaneously is broken.
I'm not whether to merge this pull request.

**Pull request closed without merging**
