### PR TITLE
Update commands.sh

### PR DESCRIPTION
**Pull request by jarriztg**

### CODE REVIEW

**Comment by danog** [comment]
I would also merge this if it weren't for https://github.com/topkecleon/telegram-bot-bash/pull/20/files#diff-cff726f76c6f00ba85e2471beb5fe74eR11 (the user id must not have a $ in front of it) and https://github.com/topkecleon/telegram-bot-bash/pull/20/files#diff-cff726f76c6f00ba85e2471beb5fe74eL73 (this breaks interactive commands).

**Comment by jarriztg** [comment]
wtf ? i have this and its functional. test it

**Comment by jarriztg** [comment]
ok which line ?

**Comment by jarriztg** [comment]
ok. was already fixed, but im adding some.. wait me

**Comment by jarriztg** [comment]
ok, already, USER[ID] is from id, isnt chat id
CHAT[ID] get the ID from the current chat

**Comment by jarriztg** [comment]
and kick me added

**Comment by danog** [comment]
Ok, but please restore https://github.com/topkecleon/telegram-bot-bash/pull/20/files#diff-cff726f76c6f00ba85e2471beb5fe74eL74

**Comment by jarriztg** [comment]
already

**Pull request merged**
