### PR TITLE
functions in bash added and colors

### PR DESCRIPTION
**Pull request by jarriztg**

### CODE REVIEW

**Comment by danog** [comment]
I would merge this if it weren't for https://github.com/topkecleon/telegram-bot-bash/pull/19/files#diff-46ae171ca9901598edd9c7df0863188eR296
The VAR=$() is used to assign the value of a variable to the command between the brackets, and since there is no command called OWNER this won't work: to assign the value of a variable to another variable use VAR=$VAR.

**Comment by danog** [comment]
Looks fine to me. You could also add CHAT[FIRST_NAME], CHAT[LAST_NAME] (that should make some order :)

**Comment by jarriztg** [comment]
CHAT[FIRST_NAME] its stranger :P its function to user, in a chat you cant get the chat first name, but the title yes

**Comment by jarriztg** [comment]
maybe i will add most functions in a future ;) im working with iicc1

**Pull request merged**
