### PR TITLE
information about the bot

### PR DESCRIPTION
**Pull request by jarriztg**

### CODE REVIEW

**Comment by topkecleon** [comment]
You want to query the API three times for the same exact information?
Why not query once and pull the info from the single result?

**Comment by jarriztg** [comment]
?

**Comment by TiagoDanin** [comment]
@jarriztg
Run bot > `while startbot` is true..............> get "process_client" > request API "getMe"
..............> `while startbot` continues true > get "process_client"  > AGAIN request API "getMe"

This let the bot slow,
Suggestion: Create a function to execute the request("getMe") and add along with `$res`

**Comment by topkecleon** [comment]
Why not learn from otouto?
On startup, do the getMe request and store it. Then get whatever information you need later from wherever you put it.

**Comment by jarriztg** [comment]
@topkecleon but the bot can do a file with the dates (id. user, etc) and load the file ? :P

**Comment by topkecleon** [comment]
I can't understand that message.

Use a single getMe call and set the bot info variables with that.

**Comment by JuanPotato** [comment]
this tbh fam

**Pull request closed without merging**
